<a href="https://colab.research.google.com/github/aryaraut13/100-days-of-aiml/blob/main/day%201%20-numpy" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Day 01 — NumPy | 100 Days of AI/ML

import numpy as np

# ── Arrays: the atomic unit of all ML ──────────────────────
arr    = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Shape:", matrix.shape)
print("Reshape →", matrix.reshape(3, 2).shape)

# ── Broadcasting: the magic that replaces loops ─────────────
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

result = a + b
print("\nBroadcast result (3,) + (3,1) → (3,3):")
print(result)
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]

# ── Why this matters for ML ──────────────────────────────────
data    = np.random.randn(100, 5)
weights = np.random.randn(5, 1)
preds   = data @ weights

print(f"\ndata {data.shape} @ weights {weights.shape} = preds {preds.shape}")
print("↑ This is what every ML model does. Millions of times per second.")

Shape: (2, 3)
Reshape → (3, 2)

Broadcast result (3,) + (3,1) → (3,3):
[[11 12 13]
 [21 22 23]
 [31 32 33]]

data (100, 5) @ weights (5, 1) = preds (100, 1)
↑ This is what every ML model does. Millions of times per second.
